-- Order of DROPS in case we wreck it:

-- DROP TABLE IF EXISTS CUSTOMER_PRODUCTS;
-- DROP TABLE IF EXISTS ORDER_PRODUCT_RETURNS;
-- DROP TABLE IF EXISTS WAREHOUSE_PRODUCTS;
-- DROP TABLE IF EXISTS WAREHOUSES;
-- DROP TABLE IF EXISTS TRANSACTIONS;
-- DROP TABLE IF EXISTS ORDER_PRODUCTS;
-- DROP TABLE IF EXISTS PRODUCTS;
-- DROP TABLE IF EXISTS ORDERS;
-- DROP TABLE IF EXISTS SELLERS;
-- DROP TABLE IF EXISTS CUSTOMERS;
-- DROP TABLE IF EXISTS USER_PHONES;
-- DROP TABLE IF EXISTS USERS;
SET DEFINE OFF;

CREATE TABLE IF NOT EXISTS USERS (
    USER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    DATE_JOINED DATE DEFAULT SYSDATE,
    CONSTRAINT VALID_EMAIL CHECK (
        REGEXP_LIKE(
            EMAIL, 
            '^[0-9a-zA-Z\._-]+@[a-zA-Z0-9]+(\.[a-zA-Z]{2,12}){1,3}$'
        )
    ),
    CONSTRAINT USER_ID PRIMARY KEY (USER_ID)
);


CREATE TABLE IF NOT EXISTS USER_PHONES (
    USER_PHONE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    USER_ID NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE NOT NULL,
    PHONE CHAR(10) UNIQUE NOT NULL, 
    CONSTRAINT ONLY_DIGITS CHECK (
        REGEXP_LIKE(
            PHONE, 
            '[0-9]{10}'
        )
    ),
    CONSTRAINT USER_PHONE_ID PRIMARY KEY (USER_PHONE_ID)
);

CREATE TABLE IF NOT EXISTS SELLERS (
    SELLER_ID NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE UNIQUE NOT NULL,
    SELLER_NAME VARCHAR2(100) NOT NULL,
    SELLER_BIO VARCHAR2(500),
    SELLER_RATING NUMBER(1,1) DEFAULT 0,
    TOTAL_SALES NUMBER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID NUMBER REFERENCES USERS(USER_ID) ON DELETE CASCADE UNIQUE NOT NULL,
    BILLING_STREET_1 VARCHAR2(50) NOT NULL,
    BILLING_STREET_2 VARCHAR2(50),
    BILLING_CITY VARCHAR2(50) NOT NULL,
    BILLING_STATE CHAR(2) NOT NULL,
    BILLING_ZIP CHAR(5) NOT NULL,
    SHIPPING_STREET_1 VARCHAR2(50) NOT NULL,
    SHIPPING_STREET_2 VARCHAR2(50),
    SHIPPING_CITY VARCHAR2(50) NOT NULL,
    SHIPPING_STATE CHAR(2) NOT NULL,
    SHIPPING_ZIP CHAR(5) NOT NULL,
    CONSTRAINT VALID_BILLING_ZIP CHECK (REGEXP_LIKE(BILLING_ZIP, '^[0-9]{5}$')),
    CONSTRAINT VALID_SHIPPING_ZIP CHECK (REGEXP_LIKE(SHIPPING_ZIP, '^[0-9]{5}$')),
    CONSTRAINT VALID_BILLING_STATE CHECK (REGEXP_LIKE(BILLING_STATE,'^[A-Z]{2}$')),
    CONSTRAINT VALID_SHIPPING_STATE CHECK (REGEXP_LIKE(SHIPPING_STATE,'^[A-Z]{2}$'))
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    SELLER_ID REFERENCES SELLERS(SELLER_ID) ON DELETE CASCADE NOT NULL,
    SUPPLIER_ID REFERENCES SELLERS(SELLER_ID) ON DELETE SET NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    PRODUCT_DESCRIPTION VARCHAR2(500) NOT NULL,
    PRICE NUMBER(6,2) NOT NULL, 
    CATEGORY VARCHAR2(30) NOT NULL,
    DATE_ADDED DATE DEFAULT SYSDATE NOT NULL,
    PUBLISHED NUMBER(1,0) DEFAULT 0,
    MARKUP NUMBER(3,2) DEFAULT 0,
    AVERAGE_RATING NUMBER(1,1) DEFAULT 0,
    CONSTRAINT PRODUCT_ID PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID) NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,
    ORDER_STATUS VARCHAR2(10) NOT NULL,
    BILLING_STREET_1 VARCHAR2(50) NOT NULL,
    BILLING_STREET_2 VARCHAR2(50),
    BILLING_CITY VARCHAR2(50) NOT NULL,
    BILLING_STATE CHAR(2) NOT NULL,
    BILLING_ZIP CHAR(5) NOT NULL,
    SHIPPING_STREET_1 VARCHAR2(50) NOT NULL,
    SHIPPING_STREET_2 VARCHAR2(50),
    SHIPPING_CITY VARCHAR2(50) NOT NULL,
    SHIPPING_STATE CHAR(2) NOT NULL,
    SHIPPING_ZIP CHAR(5) NOT NULL,
    CONSTRAINT VALID_ORDER_BILLING_ZIP CHECK (REGEXP_LIKE(BILLING_ZIP, '^[0-9]{5}$')),
    CONSTRAINT VALID_ORDER_SHIPPING_ZIP CHECK (REGEXP_LIKE(SHIPPING_ZIP, '^[0-9]{5}$')),
    CONSTRAINT VALID_ORDER_BILLING_STATE CHECK (REGEXP_LIKE(BILLING_STATE,'^[A-Z]{2}$')),
    CONSTRAINT VALID_ORDER_SHIPPING_STATE CHECK (REGEXP_LIKE(SHIPPING_STATE,'^[A-Z]{2}$')),
    CONSTRAINT VALID_ORDER_STATUS CHECK (
        ORDER_STATUS IN ('pending', 'shipped', 'delivered', 'cancelled', 'returned')),
    CONSTRAINT ORDER_ID PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    WAREHOUSE_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    LOCATION_NAME VARCHAR(30) UNIQUE NOT NULL,
    BILLING_STREET_1 VARCHAR2(50) NOT NULL,
    BILLING_STREET_2 VARCHAR2(50),
    BILLING_CITY VARCHAR2(50) NOT NULL,
    BILLING_STATE CHAR(2) NOT NULL,
    BILLING_ZIP CHAR(5) NOT NULL,
    SHIPPING_STREET_1 VARCHAR2(50) NOT NULL,
    SHIPPING_STREET_2 VARCHAR2(50),
    SHIPPING_CITY VARCHAR2(50) NOT NULL,
    SHIPPING_STATE CHAR(2) NOT NULL,
    SHIPPING_ZIP CHAR(5) NOT NULL,
    CONSTRAINT VALID_WAREHOUSE_BILLING_ZIP CHECK (REGEXP_LIKE(BILLING_ZIP, '^[0-9]{5}$')),
    CONSTRAINT VALID_WAREHOUSE_SHIPPING_ZIP CHECK (REGEXP_LIKE(SHIPPING_ZIP, '^[0-9]{5}$')),
    CONSTRAINT VALID_WAREHOUSE_BILLING_STATE CHECK (REGEXP_LIKE(BILLING_STATE,'^[A-Z]{2}$')),
    CONSTRAINT VALID_WAREHOUSE_SHIPPING_STATE CHECK (REGEXP_LIKE(SHIPPING_STATE,'^[A-Z]{2}$')),
    CONSTRAINT WAREHOUSE_ID PRIMARY KEY (WAREHOUSE_ID)
);


CREATE TABLE IF NOT EXISTS WAREHOUSE_PRODUCTS (
    WAREHOUSE_PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    WAREHOUSE_ID NUMBER REFERENCES WAREHOUSES(WAREHOUSE_ID) ON DELETE SET NULL NOT NULL,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE SET NULL NOT NULL,
    QTY INT NOT NULL,
    RESTOCK_THRESHOLD INT DEFAULT 0,
    LAST_RESTOCK_DATE DATE DEFAULT SYSDATE,
    NEXT_RESTOCK_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT WAREHOUSE_PRODUCT_NON_NEGATIVE_QTY CHECK (QTY >= 0),
    CONSTRAINT WAREHOUSE_PRODUCT_ID PRIMARY KEY (WAREHOUSE_PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_PRODUCTS (
    ORDER_PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID) ON DELETE SET NULL NOT NULL,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE SET NULL NOT NULL,
    QTY INT NOT NULL,
    TRACKING_NUMBER VARCHAR2(36) DEFAULT (
        SUBSTR(RAWTOHEX(SYS_GUID()), 1, 8) || '-' ||
        SUBSTR(RAWTOHEX(SYS_GUID()), 9, 4) || '-' ||
        SUBSTR(RAWTOHEX(SYS_GUID()), 13, 4) || '-' ||
        SUBSTR(RAWTOHEX(SYS_GUID()), 17, 4) || '-' ||
        SUBSTR(RAWTOHEX(SYS_GUID()), 21)
    ) UNIQUE,
    ESTIMATED_DELIVERY_DATE DATE, 
    DELIVERY_DATE DATE,
    CONSTRAINT ORDER_PRODUCT_NON_NEGATIVE_QTY CHECK (QTY >= 0),
    CONSTRAINT ORDER_PRODUCT_ID PRIMARY KEY (ORDER_PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_ID NUMBER REFERENCES ORDERS(ORDER_ID) ON DELETE SET NULL NOT NULL,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE SET NULL NOT NULL,
    DATE_INITIATED DATE DEFAULT SYSDATE NOT NULL,
    LAST_MODIFIED DATE DEFAULT SYSDATE NOT NULL,
    AMT NUMBER(6,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(8) NOT NULL,
    PAYMENT_STATUS VARCHAR2(8) NOT NULL,
    CONSTRAINT TRANSACTION_NONZERO_AMT CHECK (AMT > 0),
    CONSTRAINT TRANSACTION_VALID_PAYMENT_METHOD CHECK (
        PAYMENT_METHOD IN ('card', 'giftcard', 'paypal')),
    CONSTRAINT TRANSACTION_VALID_PAYMENT_STATUS CHECK (
        PAYMENT_STATUS IN ('pending', 'declined', 'refunded', 'success')),
    CONSTRAINT TRANSACTION_ID PRIMARY KEY (TRANSACTION_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_PRODUCT_RETURNS (
    ORDER_PRODUCT_RETURN_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ORDER_PRODUCT_ID NUMBER REFERENCES ORDER_PRODUCTS(ORDER_PRODUCT_ID) ON DELETE SET NULL NOT NULL,
    TRANSACTION_ID NUMBER REFERENCES TRANSACTIONS(TRANSACTION_ID),
    RETURN_DATE DATE DEFAULT SYSDATE NOT NULL,
    RETURN_REASON VARCHAR2(150) NOT NULL,
    RETURN_STATUS VARCHAR2(15) NOT NULL,
    QTY INT NOT NULL,
    CONSTRAINT ORDER_PRODUCT_RETURN_VALID_RETURN_STATUS CHECK (
        RETURN_STATUS IN ('pending', 'cancelled', 'complete', 'deleted', 'under_review')),
    CONSTRAINT ORDER_PRODUCT_RETURN_ID PRIMARY KEY (ORDER_PRODUCT_RETURN_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_PRODUCTS (
    CUSTOMER_PRODUCT_ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID NUMBER REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE NOT NULL,
    PRODUCT_ID NUMBER REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE SET NULL NOT NULL,
    LIKED BOOLEAN DEFAULT FALSE NOT NULL,
    DATE_LIKED DATE,
    RATING BOOLEAN DEFAULT FALSE NOT NULL,
    REVIEW VARCHAR2(250),
    REVIEW_DATE DATE,
    DATE_LAST_PURCHASED DATE,
    CONSTRAINT CUSTOMER_PRODUCT_UNIQUE UNIQUE ( CUSTOMER_ID, PRODUCT_ID ), 
    CONSTRAINT CUSTOMER_PRODUCT_ID PRIMARY KEY (CUSTOMER_PRODUCT_ID)
);

ALTER TABLE CUSTOMERS MODIFY (
    SHIPPING_STREET_1 ENCRYPT,
    SHIPPING_STREET_2 ENCRYPT,
    BILLING_STREET_1 ENCRYPT,
    BILLING_STREET_2 ENCRYPT
);

ALTER TABLE ORDERS MODIFY (
    SHIPPING_STREET_1 ENCRYPT,
    SHIPPING_STREET_2 ENCRYPT,
    BILLING_STREET_1 ENCRYPT,
    BILLING_STREET_2 ENCRYPT
);

ALTER TABLE USERS MODIFY (
    FIRST_NAME ENCRYPT, 
    LAST_NAME ENCRYPT,
    EMAIL ENCRYPT NO SALT
);

ALTER TABLE USER_PHONES MODIFY ( 
    PHONE ENCRYPT NO SALT
);