INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP )
SELECT 
    CUSTOMER_ID,
    'pending',
    TO_DATE('2025-12-10 17:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1,BILLING_STREET_2,BILLING_CITY,BILLING_STATE,BILLING_ZIP,
    SHIPPING_STREET_1,SHIPPING_STREET_2,SHIPPING_CITY,SHIPPING_STATE,SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('ghd97@su.edu');
    
INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP ) 
SELECT
    CUSTOMER_ID,
    'pending',
    TO_DATE('2025-12-04 12:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1,SHIPPING_STREET_2,SHIPPING_CITY,SHIPPING_STATE,SHIPPING_ZIP
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('g_hollandaise@gmail.com');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP ) 
SELECT 
    CUSTOMER_ID,
    'pending',
    TO_DATE('2025-11-28 15:45:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('ava.jared@icloud.com');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP) 
SELECT 
    CUSTOMER_ID,
    'pending',
    TO_DATE('2025-11-25 10:30:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('honk@clown.co');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP ) 
SELECT 
    CUSTOMER_ID,
    'pending',
    TO_DATE('2025-11-15 18:05:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('olumuyiwa.unigwe@hotmail.com');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP ) 
SELECT 
    CUSTOMER_ID,
    'delivered',
    TO_DATE('2025-12-10 17:15:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('olumuyiwa.unigwe@hotmail.com');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP )
SELECT 
    CUSTOMER_ID,
    'delivered',
    TO_DATE('2025-12-11 13:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('bambino-carlo@proton.me');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP )
SELECT 
    CUSTOMER_ID,
    'delivered',
    TO_DATE('2025-12-02 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('aiko.2k@gmail.com');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP )
SELECT 
    CUSTOMER_ID,
    'delivered',
    TO_DATE('2025-12-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('aiko.2k@gmail.com');

INSERT INTO ORDERS ( CUSTOMER_ID, ORDER_STATUS, ORDER_DATE, BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP, SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP )
SELECT 
    CUSTOMER_ID,
    'delivered',
    TO_DATE('2025-11-11 11:11:11', 'YYYY-MM-DD HH24:MI:SS'),
    BILLING_STREET_1, BILLING_STREET_2, BILLING_CITY, BILLING_STATE, BILLING_ZIP,
    SHIPPING_STREET_1, SHIPPING_STREET_2, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_ZIP 
FROM CUSTOMERS WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('aiko.2k@gmail.com');