INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KY_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('Big Red Nose'),
           6300,
           200,
           SYSDATE,
           SYSDATE + 30
           );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KY_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('Big Red Nose'),
           6300,
           200,
           SYSDATE,
           SYSDATE + 30
           );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KY_3'),
           GET_PRODUCT_BY_PRODUCT_NAME('WetLapel'),
           1000,
           250,
           SYSDATE,
           SYSDATE + 30 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KY_3'),
           GET_PRODUCT_BY_PRODUCT_NAME('Glycine'),
           10000,
           2500,
           SYSDATE,
           SYSDATE + 30 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KY_3'),
           GET_PRODUCT_BY_PRODUCT_NAME('Hydantoin'),
           20000,
           2000,
           SYSDATE,
           SYSDATE + 30 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('PA_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('Italian Christmas Donkey'),
           50,
           5,
           SYSDATE,
           SYSDATE + 365 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('DE_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('Glycine'),
           32250,
           15540,
           SYSDATE,
           SYSDATE + 30 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('DE_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('Hydantoin'),
           60000,
           25000,
           SYSDATE,
           SYSDATE + 30 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KS_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('Maliqawah Original Green Tea'),
           45000,
           5000,
           SYSDATE,
           SYSDATE + 30 );

INSERT INTO WAREHOUSE_PRODUCTS (
    WAREHOUSE_ID,
    PRODUCT_ID,
    QTY,
    RESTOCK_THRESHOLD,
    LAST_RESTOCK_DATE,
    NEXT_RESTOCK_DATE
) VALUES ( GET_WAREHOUSE_BY_LOCATION_NAME('KS_1'),
           GET_PRODUCT_BY_PRODUCT_NAME('WetLapel Flower'),
           4500,
           500,
           SYSDATE,
           SYSDATE + 30 );