INSERT INTO TRANSACTIONS ( ORDER_ID, CUSTOMER_ID, AMT, PAYMENT_METHOD, PAYMENT_STATUS ) 
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    SUM((PRICE * (1 + (MARKUP/100))) * QTY),
    'card',
    'pending'
    FROM PRODUCTS NATURAL JOIN ORDER_PRODUCTS NATURAL JOIN ORDERS 
    WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('g_hollandaise@gmail.com') GROUP BY ORDER_ID, CUSTOMER_ID;

INSERT INTO TRANSACTIONS ( ORDER_ID, CUSTOMER_ID, AMT, PAYMENT_METHOD, PAYMENT_STATUS ) 
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    SUM((PRICE * (1 + (MARKUP/100))) * QTY),
    'card',
    'pending'
    FROM PRODUCTS NATURAL JOIN ORDER_PRODUCTS NATURAL JOIN ORDERS 
    WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('ghd97@su.edu') GROUP BY ORDER_ID, CUSTOMER_ID;

INSERT INTO TRANSACTIONS ( ORDER_ID, CUSTOMER_ID, AMT, PAYMENT_METHOD, PAYMENT_STATUS ) 
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
SUM((PRICE * (1 + (MARKUP/100))) * QTY),
    'card',
    'success'
    FROM PRODUCTS NATURAL JOIN ORDER_PRODUCTS NATURAL JOIN ORDERS 
    WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('honk@clown.co') GROUP BY ORDER_ID, CUSTOMER_ID;
    

INSERT INTO TRANSACTIONS ( ORDER_ID, CUSTOMER_ID, AMT, PAYMENT_METHOD, PAYMENT_STATUS ) 
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    SUM((PRICE * (1 + (MARKUP/100))) * QTY),
    'card',
    'pending'
    FROM PRODUCTS NATURAL JOIN ORDER_PRODUCTS NATURAL JOIN ORDERS 
    WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('bambino-carlo@proton.me') GROUP BY ORDER_ID, CUSTOMER_ID;

-- Aiko paying for all outstanding orders
INSERT INTO TRANSACTIONS ( ORDER_ID, CUSTOMER_ID, AMT, PAYMENT_METHOD, PAYMENT_STATUS ) 
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    SUM((PRICE * (1 + (MARKUP/100))) * QTY) AS AMT,
    'card' AS PAYMENT_METHOD,
    'success' AS PAYMENT_STATUS
    FROM PRODUCTS NATURAL JOIN ORDER_PRODUCTS NATURAL JOIN ORDERS 
    WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('aiko.2k@gmail.com') GROUP BY ORDER_ID, CUSTOMER_ID;

-- Processing a return transaction.
INSERT INTO TRANSACTIONS ( ORDER_ID, CUSTOMER_ID, AMT, PAYMENT_METHOD, PAYMENT_STATUS )
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    SUM((PRICE * (1 + MARKUP)) * ORDER_PRODUCT_RETURNS.QTY),
    'card',
    'success'
    FROM PRODUCTS NATURAL JOIN ORDER_PRODUCTS NATURAL JOIN ORDER_PRODUCT_RETURNS
    WHERE CUSTOMER_ID = GET_USER_BY_EMAIL('AIKO.2K@GMAIL.COM') AND ORDER_PRODUCT_RETURNS.RETURN_STATUS = 'complete';